export type Language = 'javascript' | 'python' | 'cpp' | 'java';
export type ValueType = 'int' | 'number' | 'boolean' | 'string' | 'char' | 'int[]' | 'string[]' | 'char[]' | 'int[][]' | 'string[][]';

export interface ChallengeTest { input: unknown[]; expected: unknown; }
export interface Challenge {
  id: string; title: string; description: string; difficulty: 'easy' | 'medium' | 'hard';
  category: string; functionName: string; propertyTier: string; argTypes: ValueType[]; returnType: ValueType;
  starters: Record<Language, string>; examples: Array<{ input: string; output: string; explanation?: string }>;
  constraints?: string; publicTests: ChallengeTest[]; hiddenTests: ChallengeTest[];
  validator?: 'two-sum' | 'unordered-nested';
}

const starters = (js: string, py: string, cpp: string, java: string): Record<Language, string> => ({ javascript: js, python: py, cpp, java });
const p = (x: Challenge) => x;

export const challenges: Challenge[] = [
  p({id:'two-sum',title:'Two Sum',description:'Return the indices of two distinct numbers whose sum equals target.',difficulty:'easy',category:'arrays',functionName:'twoSum',propertyTier:'brown',argTypes:['int[]','int'],returnType:'int[]',validator:'two-sum',starters:starters('function twoSum(nums, target) {\n  // your code\n  return [];\n}','def twoSum(nums, target):\n    # your code\n    return []','vector<int> twoSum(vector<int> nums, int target) {\n  return {};\n}','static int[] twoSum(int[] nums, int target) {\n  return new int[]{};\n}'),examples:[{input:'nums = [2,7,11,15], target = 9',output:'[0,1]'}],publicTests:[{input:[[2,7,11,15],9],expected:[0,1]},{input:[[3,2,4],6],expected:[1,2]}],hiddenTests:[{input:[[-3,4,3,90],0],expected:[0,2]}]}),
  p({id:'reverse-string',title:'Reverse String',description:'Return the characters in reverse order.',difficulty:'easy',category:'strings',functionName:'reverseString',propertyTier:'brown',argTypes:['char[]'],returnType:'char[]',starters:starters('function reverseString(s) {\n  // your code\n  return s;\n}','def reverseString(s):\n    # your code\n    return s','vector<string> reverseString(vector<string> s) {\n  return s;\n}','static String[] reverseString(String[] s) {\n  return s;\n}'),examples:[{input:'["h","e","l","l","o"]',output:'["o","l","l","e","h"]'}],publicTests:[{input:[['h','e','l','l','o']],expected:['o','l','l','e','h']}],hiddenTests:[{input:[['A','b']],expected:['b','A']}]}),
  p({id:'valid-palindrome',title:'Valid Palindrome',description:'Return whether the alphanumeric characters form a palindrome, ignoring case.',difficulty:'easy',category:'strings',functionName:'isPalindrome',propertyTier:'lightblue',argTypes:['string'],returnType:'boolean',starters:starters('function isPalindrome(s) {\n  return false;\n}','def isPalindrome(s):\n    return False','bool isPalindrome(string s) {\n  return false;\n}','static boolean isPalindrome(String s) {\n  return false;\n}'),examples:[{input:'"A man, a plan, a canal: Panama"',output:'true'}],publicTests:[{input:['A man, a plan, a canal: Panama'],expected:true},{input:['race a car'],expected:false}],hiddenTests:[{input:[' '],expected:true}]}),
  p({id:'contains-duplicate',title:'Contains Duplicate',description:'Return true if an integer appears more than once.',difficulty:'easy',category:'arrays',functionName:'containsDuplicate',propertyTier:'lightblue',argTypes:['int[]'],returnType:'boolean',starters:starters('function containsDuplicate(nums) {\n  return false;\n}','def containsDuplicate(nums):\n    return False','bool containsDuplicate(vector<int> nums) {\n  return false;\n}','static boolean containsDuplicate(int[] nums) {\n  return false;\n}'),examples:[{input:'[1,2,3,1]',output:'true'}],publicTests:[{input:[[1,2,3,1]],expected:true},{input:[[1,2,3,4]],expected:false}],hiddenTests:[{input:[[]],expected:false}]}),
  p({id:'best-time-stock',title:'Best Time to Buy and Sell Stock',description:'Return the maximum profit from one buy followed by one sell.',difficulty:'easy',category:'arrays',functionName:'maxProfit',propertyTier:'lightblue',argTypes:['int[]'],returnType:'int',starters:starters('function maxProfit(prices) {\n  return 0;\n}','def maxProfit(prices):\n    return 0','int maxProfit(vector<int> prices) {\n  return 0;\n}','static int maxProfit(int[] prices) {\n  return 0;\n}'),examples:[{input:'[7,1,5,3,6,4]',output:'5'}],publicTests:[{input:[[7,1,5,3,6,4]],expected:5},{input:[[7,6,4,3,1]],expected:0}],hiddenTests:[{input:[[2,4,1]],expected:2}]}),
  p({id:'longest-substring',title:'Longest Substring Without Repeating Characters',description:'Return the length of the longest substring without repeated characters.',difficulty:'medium',category:'strings',functionName:'lengthOfLongestSubstring',propertyTier:'pink',argTypes:['string'],returnType:'int',starters:starters('function lengthOfLongestSubstring(s) {\n  return 0;\n}','def lengthOfLongestSubstring(s):\n    return 0','int lengthOfLongestSubstring(string s) {\n  return 0;\n}','static int lengthOfLongestSubstring(String s) {\n  return 0;\n}'),examples:[{input:'"abcabcbb"',output:'3'}],publicTests:[{input:['abcabcbb'],expected:3},{input:['bbbbb'],expected:1},{input:['pwwkew'],expected:3}],hiddenTests:[{input:[''],expected:0}]}),
  p({id:'three-sum',title:'3Sum',description:'Return all unique triplets whose values sum to zero.',difficulty:'medium',category:'arrays',functionName:'threeSum',propertyTier:'orange',argTypes:['int[]'],returnType:'int[][]',validator:'unordered-nested',starters:starters('function threeSum(nums) {\n  return [];\n}','def threeSum(nums):\n    return []','vector<vector<int>> threeSum(vector<int> nums) {\n  return {};\n}','static int[][] threeSum(int[] nums) {\n  return new int[][]{};\n}'),examples:[{input:'[-1,0,1,2,-1,-4]',output:'[[-1,-1,2],[-1,0,1]]'}],publicTests:[{input:[[-1,0,1,2,-1,-4]],expected:[[-1,-1,2],[-1,0,1]]}],hiddenTests:[{input:[[0,0,0]],expected:[[0,0,0]]}]}),
  p({id:'container-water',title:'Container With Most Water',description:'Return the maximum water area between two heights.',difficulty:'medium',category:'arrays',functionName:'maxArea',propertyTier:'orange',argTypes:['int[]'],returnType:'int',starters:starters('function maxArea(height) {\n  return 0;\n}','def maxArea(height):\n    return 0','int maxArea(vector<int> height) {\n  return 0;\n}','static int maxArea(int[] height) {\n  return 0;\n}'),examples:[{input:'[1,8,6,2,5,4,8,3,7]',output:'49'}],publicTests:[{input:[[1,8,6,2,5,4,8,3,7]],expected:49}],hiddenTests:[{input:[[1,1]],expected:1}]}),
  p({id:'group-anagrams',title:'Group Anagrams',description:'Group strings that are anagrams.',difficulty:'medium',category:'strings',functionName:'groupAnagrams',propertyTier:'red',argTypes:['string[]'],returnType:'string[][]',validator:'unordered-nested',starters:starters('function groupAnagrams(strs) {\n  return [];\n}','def groupAnagrams(strs):\n    return []','vector<vector<string>> groupAnagrams(vector<string> strs) {\n  return {};\n}','static String[][] groupAnagrams(String[] strs) {\n  return new String[][]{};\n}'),examples:[{input:'["eat","tea","tan","ate","nat","bat"]',output:'[["bat"],["nat","tan"],["ate","eat","tea"]]'}],publicTests:[{input:[['eat','tea','tan','ate','nat','bat']],expected:[['eat','tea','ate'],['tan','nat'],['bat']]}],hiddenTests:[{input:[['']],expected:[['']]}]}),
  p({id:'coin-change',title:'Coin Change',description:'Return the fewest coins needed to make the amount, or -1.',difficulty:'medium',category:'dp',functionName:'coinChange',propertyTier:'red',argTypes:['int[]','int'],returnType:'int',starters:starters('function coinChange(coins, amount) {\n  return -1;\n}','def coinChange(coins, amount):\n    return -1','int coinChange(vector<int> coins, int amount) {\n  return -1;\n}','static int coinChange(int[] coins, int amount) {\n  return -1;\n}'),examples:[{input:'coins = [1,2,5], amount = 11',output:'3'}],publicTests:[{input:[[1,2,5],11],expected:3},{input:[[2],3],expected:-1}],hiddenTests:[{input:[[1],0],expected:0}]}),
  p({id:'median-arrays',title:'Median of Two Sorted Arrays',description:'Return the median of two sorted arrays.',difficulty:'hard',category:'arrays',functionName:'findMedianSortedArrays',propertyTier:'yellow',argTypes:['int[]','int[]'],returnType:'number',starters:starters('function findMedianSortedArrays(a, b) {\n  return 0;\n}','def findMedianSortedArrays(a, b):\n    return 0','double findMedianSortedArrays(vector<int> a, vector<int> b) {\n  return 0;\n}','static double findMedianSortedArrays(int[] a, int[] b) {\n  return 0;\n}'),examples:[{input:'[1,3], [2]',output:'2'}],publicTests:[{input:[[1,3],[2]],expected:2},{input:[[1,2],[3,4]],expected:2.5}],hiddenTests:[{input:[[],[1]],expected:1}]}),
  p({id:'trapping-rain',title:'Trapping Rain Water',description:'Return how much rain water is trapped by the elevation map.',difficulty:'hard',category:'arrays',functionName:'trap',propertyTier:'green',argTypes:['int[]'],returnType:'int',starters:starters('function trap(height) {\n  return 0;\n}','def trap(height):\n    return 0','int trap(vector<int> height) {\n  return 0;\n}','static int trap(int[] height) {\n  return 0;\n}'),examples:[{input:'[0,1,0,2,1,0,1,3,2,1,2,1]',output:'6'}],publicTests:[{input:[[0,1,0,2,1,0,1,3,2,1,2,1]],expected:6}],hiddenTests:[{input:[[4,2,0,3,2,5]],expected:9}]}),
  p({id:'longest-valid-parentheses',title:'Longest Valid Parentheses',description:'Return the length of the longest valid parentheses substring.',difficulty:'hard',category:'dp',functionName:'longestValidParentheses',propertyTier:'darkblue',argTypes:['string'],returnType:'int',starters:starters('function longestValidParentheses(s) {\n  return 0;\n}','def longestValidParentheses(s):\n    return 0','int longestValidParentheses(string s) {\n  return 0;\n}','static int longestValidParentheses(String s) {\n  return 0;\n}'),examples:[{input:'")()())"',output:'4'}],publicTests:[{input:['(()'],expected:2},{input:[')()())'],expected:4}],hiddenTests:[{input:[''],expected:0}]})
];

export const challengeById = (id: string) => challenges.find(c => c.id === id);
export function challengeForTier(tier: string): Challenge {
  const key = tier.toLowerCase();
  const colorTiers: Record<string, string> = { '#8b4513':'brown', '#87ceeb':'lightblue', '#ff69b4':'pink', '#ff8c00':'orange', '#dc143c':'red', '#ffd700':'yellow', '#228b22':'green', '#00008b':'darkblue', '#000000':'orange', '#ffffff':'pink' };
  const normalized = colorTiers[key] || key.replace(/[^a-z]/g, '');
  const matches = challenges.filter(c => c.propertyTier === normalized);
  return matches[Math.floor(Math.random() * matches.length)] || challenges[0];
}
export function publicChallenge(c: Challenge) {
  const { publicTests: _public, hiddenTests: _hidden, argTypes: _args, returnType: _ret, validator: _validator, starters: functionSignatures, ...safe } = c;
  return { ...safe, functionSignatures };
}




